server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB   #单个限制文件大小限制
      max-request-size: 10MB #一次请求大小的限制，一个请求可以有多个文件


#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:               #禁止主机名访问，通过ip访问
    ip-address: 127.0.0.1
    prefer-ip-address: true
